### PR TITLE
Add Steer and Throttle Joysticks

### PR DESCRIPTION
**Pull request by Geotricity**
@droid-101 said that he would like the driver to use two joysticks and the operator to use a controller.

This pull request will:

 - Move dualshock controller to Operator
- Add steer and throttle joysticks to Driver

### CODE REVIEW

**Review by bricktrooper — APPROVED** [review]
Looks good man.  Btw the USB ports on the computer can be kinda finicky.  If you look in the purple driver station cabinet you should find a USB hub that you can connect all the sticks and controllers to.  If the port numbers are wrong you can reorder it in the driver station app.  Saves you the trouble of changing the code.

**Review by danielzyy — APPROVED** [review]
Looks good, may have to adjust your deadzone threshold now if the old value was tuned for the controller and not the joystick.

**Comment by bricktrooper** [comment]
> Looks good, may have to adjust your deadzone threshold now if the old value was tuned for the controller and not the joystick.

Yeah to be honest I think they could probably just experimentally pick a deadzone whenever the drivetrain is finished.  The sticks sometimes act weird especially if dust gets inside.  Lol I remember we had a "phantom stick" that would just cause the robot to move on its own.

**Comment by Geotricity** [comment]
> Looks good man. Btw the USB ports on the computer can be kinda finicky. If you look in the purple driver station cabinet you should find a USB hub that you can connect all the sticks and controllers to.

Thanks. One of the USB ports on the computer is completely broken, even missing the plastic bit on the inside lol.

**Pull request merged**
